#!/usr/bin/env bash
# set up an ngnix server

apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'
nginx -g "listen"
nginx -s reload # reloads it so the configuration changes take effect
