#!/usr/bin/env bash
# set up an ngnix server

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
fourohfourline="\terror_page 404 /error404.html;\n\n\tlocation / {"
tricked_you="\tserver_name hiredoug.tech;\n\tlocation \/redirect_me {\n\treturn 301 https:\/\/www.youtube.com\/\/watch\?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "s|^\tserver_name _;|$tricked_you|" /etc/nginx/sites-available/default
sudo sed -i "s|^tlocation / {|$fourohfourline|" /etc/nginx/sites-available/default
sudo rm /var/www/html/*.html
sudo echo "Hello World" | sudo tee /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
sudo /etc/init.d/nginx restart
