#!/usr/bin/env bash
# this script configures a load balancer

sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install haproxy
echo "
frontend http_web
    bind *:80
    mode http
    default_backend web_backend
    
backend web_backend
    balance roundrobin
    option forwardfor
    server 4939-web-01 23.20.182.171:80 check
    server 4939-web-02 34.207.205.130:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
